# Install command-line tools using Homebrew
# Usage: `brew bundle Brewfile`

# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# Install more recent versions of some OS X tools
install macvim --override-system-vim

install brew-cask
install git
install grc
install hub
install mobile-shell
install node
install readline
install reattach-to-user-namespace
install the_silver_searcher
install mackup
install tmux
install wget
install zsh

tap monochromegane/pt
install pt

# Remove outdated versions from the cellar
cleanup
