#!/usr/bin/env python

#
# This file gets executed before at the startup of a
# python shell
#
# Place this file in the root directory of your system
# and add the following to .bashrc

# export PYTHONSTARTUP="$HOME/.pythonrc"
#

# Use jedi/readline for autocompletion
try:
    from jedi.utils import setup_readline
    setup_readline()
except ImportError:
    print "Jedi not installed. Falling back to readline"
    try:
        import readline
        import rlcompleter
        readline.parse_and_bind("tab: complete")
    except ImportError:
        print "Readline not installed"


def ppdict(d):
    """Pretty Print for Dicts"""
    print '{'
    keys = d.keys()
    keys.sort()
    for k in keys:
        spacing = " "  # * (16-(len(repr(k))+1))
        print "%s:%s%s," % (repr(k), spacing, repr(d[k]))
    print '}'
