# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="kennethreitz"

# Example aliases
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Include custom aliases
. ~/aliases.zsh

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(osx git python)

source $ZSH/oh-my-zsh.sh

export PATH=$PATH:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin
export PATH=$PATH:/usr/local/AWS-ElasticBeanstalk-CLI-2.5.1/eb/macosx/python2.7/:/usr/local/share/npm/bin
export PATH=$PATH:/opt/local/bin:/opt/local/sbin
export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/9.3/bin

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# Config for virtualenvwrapper
#export WORKON_HOME=~/Envs
#source /usr/local/bin/virtualenvwrapper.sh

# Setting up pip download cache
export PIP_DOWNLOAD_CACHE=~/.pip-download-cache

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help"
#export DOCKER_HOST=tcp://localhost:4243
#export DOCKER_HOST=tcp://192.168.59.103:2375
export DOCKER_HOST=tcp://$(boot2docker ip 2>/dev/null):2375

# Setup custom imports when you launch a python shell
export PYTHONSTARTUP="$HOME/.pythonrc"

export LANGUAGE="en_US.UTF-8"
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# grc setup
source `brew --prefix grc`/etc/grc.bashrc

pyserv() {
    if [[ -n $1 ]] ; then
        port="$1"
    else
        port="8000"
    fi

    old_dir="$(pwd)"

    if [[ -n $2 ]] ; then
        cd $2
    fi

    screen -dmS pyserv${port} python -m SimpleHTTPServer ${port}
    echo "http://localhost:${port}"
    echo "screen -r pyserv${port}"

    if ! [[ "$(pwd)" == $old_dir ]] ; then
        cd $old_dir
    fi
}
