# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="lambda"

# Example aliases
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Include custom aliases
. ~/aliases.zsh

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
#plugins=(osx git python)

source $ZSH/oh-my-zsh.sh

export PATH=/usr/local/bin:$PATH
export PATH=$PATH:/usr/local/bin:/usr/local/git/bin
export PATH=$PATH:/usr/local/bin/emacs
export PATH=$PATH:/usr/bin:/bin:/usr/sbin:/sbin
export PATH=$PATH:/usr/local/AWS-ElasticBeanstalk-CLI-2.5.1/eb/macosx/python2.7/:/usr/local/share/npm/bin
export PATH=$PATH:/opt/local/bin:/opt/local/sbin
export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/9.3/bin

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# Editor
export EDITOR="emacsclient -t"
export VISUAL="emacsclient -c -a emacs"

# Setting up pip download cache
export PIP_DOWNLOAD_CACHE=~/.pip-download-cache

#RVM
PATH=$PATH:$HOME/.rvm/bin

export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help"
# Docker
export DOCKER_TLS_VERIFY=1
export DOCKER_CERT_PATH=/Users/kiran/.boot2docker/certs/boot2docker-vm
#export DOCKER_HOST=tcp://$(boot2docker ip 2>/dev/null):2376
export DOCKER_HOST=tcp://192.168.59.103:2376

# Setup custom imports when you launch a python shell
export PYTHONSTARTUP="$HOME/.pythonrc"

export LANGUAGE="en_US.UTF-8"
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# grc setup
source `brew --prefix grc`/etc/grc.bashrc

pyserv() {
    if [[ -n $1 ]] ; then
        port="$1"
    else
        port="8000"
    fi

    old_dir="$(pwd)"

    if [[ -n $2 ]] ; then
        cd $2
    fi

    screen -dmS pyserv${port} python -m SimpleHTTPServer ${port}
    echo "http://localhost:${port}"
    echo "screen -r pyserv${port}"

    if ! [[ "$(pwd)" == $old_dir ]] ; then
        cd $old_dir
    fi
}

# Internal IP
alias iip="ifconfig | grep -A 1 en1 | grep -e \"inet \""

acv(){
    if [ -f env/bin/activate ]; then . env/bin/activate;
    fi
}

# Perform a search and replace on current dir
sr() {
    find . -type f -exec sed -i '' s/$1/$2/g {} +
}

# Extract a specific column from shell output
# Usage: git status -s | col 2
function col {
    awk -v col=$1 '{print $col}'
}
